spring:
  application:
    name:
      LearnSpring
  datasource:
    url: jdbc:mysql://localhost:3306/learn_spring?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 186317
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
server:
  port: 8888

# MyBatis
mybatis:
  typeAliasesPackage: org.lwx.learnspring.mapper
  mapperLocations: classpath*:mappers/*Mapper.xml

jwt:
  key: mykey
  expire: 720
authorize:
  permit-urls:
    - "/login"
    - "/hello"
    - "/favicon.ico"

logging.level.root: INFO
